name: ohbemn
channels:
  - conda-forge
dependencies:
  - xarray
  - numpy
  - scipy
  - netcdf4
  - coloredlogs
  - pytest
  - pytest-benchmark
  - pytest-profiling
  - matplotlib
  - cartopy
  - cmocean
  - pyproj
  - maturin
  - jupyter
  - ipython
  - gfortran=13
  - gcc=13
  - cmake<4
